"""Add is_weekend column to closing_prices

Revision ID: 7eb36068c3cd
Revises: 
Create Date: 2025-07-04 17:39:57.752248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '7eb36068c3cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First add the column as nullable
    with op.batch_alter_table('closing_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_weekend', sa.Boolean(), nullable=True))
    
    # Create a table representation for the update
    closing_prices = table('closing_prices',
        column('date_time', sa.Date),
        column('is_weekend', sa.Boolean)
    )
    
    # Update existing records - set is_weekend based on the date
    op.execute(
        closing_prices.update().values(
            is_weekend=sa.case(
                (sa.extract('dow', closing_prices.c.date_time).in_([5, 6]), True),
                else_=False
            )
        )
    )
    
    # Now make the column not nullable
    with op.batch_alter_table('closing_prices', schema=None) as batch_op:
        batch_op.alter_column('is_weekend',
                    existing_type=sa.Boolean(),
                    nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closing_prices', schema=None) as batch_op:
        batch_op.drop_column('is_weekend')

    # ### end Alembic commands ###
